### ISSUE TITLE
Unable to close Windows365 window

### ISSUE THREAD

**Issue by MurzNN** [agam778/MS-365-Electron#203] opened 2024-03-05 06:11 UTC
When I open the Windows365 VDI interface, all works well, but I can't close the windows - pressing "x" does nothing, and there are no other ways to close the window or quit the app. The menu bar is not available (despite the "Show menu bar" mode is chosen).

Can you make closing work by clicking on the "x" window button? Thanks!

**Comment by agam778** [comment] 2024-03-21 12:43
Hi! I don't use Windows365, and since I cannot reproduce the issue, I would not be able to fix it. Closing the issue.

**Closed** 2024-03-21 12:43 UTC
